main: com.puukly.worldlies.WorldLiesInterface
name: WorldLies
version: "${VERSION}"
api-version: "1.21.11"
author: Puukly
description: The World is lying
commands:
  wli:
    description: Base command for WorldLies
    usage: "/wli help"
    aliases:
      - worldlies